#!/bin/bash
#
# Wrapper script for Slurm batch submit
# Args are submit script, outputfile, and error file
# Return the job id via stdout

SUBMIT=$1
LOGFILE=$2
ERRFILE=$3

sbatch -o $LOGFILE -e $ERRFILE $SUBMIT
