#!/bin/bash

JS=$(squeue -j $1 -o %t --noheader)

if [ -z "$JS" ] ; then
    echo "Unknown $1"
elif [[ "x$JS" == "xPD" ]] ; then
    echo "Pending"
elif [[ "x$JS" == "xR" ]] ; then
    echo "Running"
elif [[ "x$JS" == "xCG" ]] ; then
    echo "Finished"
fi
